# Use postgres/example user/password credentials
version: '3.1'

services:
  # web:
  #   build: src/Library.Api/
  #   networks:
  #     - keycloak-network
  #   ports: 
  #     - 5000:80
  #   restart: on-failure
  #   environment:
  #     - ASPNETCORE_ENVIRONMENT=Development
  #   depends_on: 
  #     - library_db
  #     - auth

  auth:
    image: keycloak/keycloak
    networks:
      - keycloak-network
    ports:
      - 8080:8080
    volumes:
      - ./imports:/opt/jboss/keycloak/imports
    environment:
      KEYCLOAK_IMPORT: /opt/jboss/keycloak/imports/realm-export.json -Dkeycloak.profile.feature.upload_scripts=enabled
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: secret
      KEYCLOAK_FRONTEND_URL: http://localhost:8080/auth
      DB_VENDOR: POSTGRES
      DB_USER: keycloak
      DB_PASSWORD: post_keycloak_pwd123
      DB_ADDR: keycloak_db
      DB_DATABASE: keycloak
      DB_PORT: 5432
    depends_on:
     - keycloak_db

  keycloak_db:
    image: postgres
    restart: always
    networks:
        - keycloak-network
    ports:
      - 5433:5432
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak 
      POSTGRES_PASSWORD: post_keycloak_pwd123

  library_db:
    image: postgres
    networks:
      - keycloak-network
    restart: always
    ports:
      - 5432:5432
    volumes: 
      - ./sql/migrations.sql:/docker-entrypoint-initdb.d/1-migrations.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    environment:
      POSTGRES_DB: library_db
      POSTGRES_PASSWORD: post_pwd123
  
networks:
  keycloak-network:
    driver: bridge