# Use postgres/example user/password credentials
version: '3.1'

services:
  library_db:
    image: postgres
    restart: always
    volumes: 
      - ./sql/migrations.sql:/docker-entrypoint-initdb.d/1-migrations.sql
      - ./sql/data.sql:/docker-entrypoint-initdb.d/2-data.sql
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: library_db
      POSTGRES_PASSWORD: post_pwd123